spring.application.name=RECOMMENDATION-SERVICE
#spring.datasource.url = jdbc:postgresql://localhost:5432/traineeDB
#spring.datasource.username = postgres
#spring.datasource.password = shubham
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

server.port=9094

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.service-url.defaultZone=${EUREKA_URL}
spring.config.import=optional:configserver:${CONFIG_SERVER_URL}
management.endpoints.web.exposure.include=*